const PRODUCTS=[
{id:'postcard',name:'小晴・星光明信片組',price:390,tag:'人氣收藏',image:'assets/hero.jpg',desc:'6 張不同氛圍的 AI 小晴限定明信片，適合收藏、送給朋友，或當作桌面小卡。'},
{id:'photobook',name:'小晴・夢境寫真集',price:690,tag:'限定作品',image:'assets/room-bed.jpg',desc:'以「房間、夕陽、夜色、夢境」為主題的數位 AI 寫真作品集。'},
{id:'wallpaper',name:'小晴・夢境桌布包',price:190,tag:'數位下載',image:'assets/room-window.jpg',desc:'手機與桌面用高解析夢境壁紙組，含晨光、夜空、窗邊與海岸氛圍。'},
{id:'artcard',name:'小晴・收藏畫卡',price:490,tag:'藝術收藏',image:'assets/character-sheet.jpg',desc:'精選 AI 藝術畫卡，適合收藏、展示或作為數位作品紀念。'},
{id:'voice',name:'小晴・晚安語音包',price:290,tag:'互動內容',image:'assets/avatar.jpg',desc:'溫柔晚安、鼓勵與日常陪伴主題的角色語音內容。'},
{id:'design',name:'小晴・夢境手機殼設計包',price:590,tag:'客製靈感',image:'assets/room-moodboard.png',desc:'一組可用於手機殼、桌布與社群封面的夢境視覺設計素材。'}
];
let cart=JSON.parse(localStorage.getItem('xiaoqing-cart')||'[]');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return 'NT$'+n.toLocaleString('zh-TW')}
function saveCart(){localStorage.setItem('xiaoqing-cart',JSON.stringify(cart));updateCartCount()}
function updateCartCount(){const n=cart.reduce((a,b)=>a+b.qty,0);$$('.cart-count').forEach(x=>x.textContent=n)}
function toast(t){const el=$('.toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.remove('show'),2200)}
function productCard(p){return `<article class="product reveal"><div class="product-img"><img src="${p.image}" alt="${p.name}"><span class="tag">${p.tag}</span></div><div class="product-body"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="product-actions"><button class="btn ghost view-product" data-id="${p.id}">看作品</button><button class="btn add-product" data-id="${p.id}">加入收藏</button></div></div></article>`}
function renderProducts(){const box=$('#products');if(box){box.innerHTML=PRODUCTS.map(productCard).join('');observeReveal();}}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const m=$('#productModal');m.querySelector('.product-detail').innerHTML=`<img src="${p.image}" alt="${p.name}"><div class="detail-copy"><span class="kicker">${p.tag}</span><h2>${p.name}</h2><p class="lead">${p.desc}</p><div class="price" style="font-size:30px;margin-top:25px">${money(p.price)}</div><div class="qty"><button class="qty-minus">−</button><b class="qty-num">1</b><button class="qty-plus">＋</button></div><button class="btn add-detail" style="width:100%">加入購物袋</button></div>`;m.dataset.id=id;m.classList.add('show');}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const old=cart.find(x=>x.id===id);if(old)old.qty+=qty;else cart.push({id,qty});saveCart();toast('已加入小晴的購物袋 ✦')}
function openCart(){const m=$('#cartModal');const list=m.querySelector('.cart-list');if(!cart.length){list.innerHTML='<div style="padding:40px;text-align:center;color:#777">購物袋還是空的。去挑一個你喜歡的小晴吧 ✦</div>'}else{list.innerHTML=cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);return `<div style="display:grid;grid-template-columns:70px 1fr auto;gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)"><img src="${p.image}" style="width:70px;height:80px;object-fit:cover;border-radius:14px"><div><b>${p.name}</b><div style="color:#777;margin-top:5px">${money(p.price)} × ${x.qty}</div></div><button class="remove-item" data-id="${x.id}" style="background:#f1eaee;border-radius:50%;width:36px;height:36px">×</button></div>`}).join('')}
const total=cart.reduce((a,x)=>a+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0);m.querySelector('.cart-total').textContent=money(total);m.classList.add('show')}
function openCheckout(){if(!cart.length){toast('請先選一個商品');return}$('#cartModal').classList.remove('show');$('#checkoutModal').classList.add('show');const summary=cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);return `${p.name} × ${x.qty} = ${money(p.price*x.qty)}`}).join('\n');$('#orderSummary').value=summary;$('#orderTotal').value=money(cart.reduce((a,x)=>a+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0));const id='XQ'+Date.now().toString(36).toUpperCase();if($('#orderId'))$('#orderId').value=id;if($('#formNext'))$('#formNext').value=(window.XIAOQING_CONFIG?.siteUrl||location.origin)+'/thank-you.html';}
function mailtoOrder(){const name=$('#orderName').value.trim(),email=$('#orderEmail').value.trim(),phone=$('#orderPhone').value.trim(),address=$('#orderAddress').value.trim(),note=$('#orderNote').value.trim();const summary=$('#orderSummary').value,total=$('#orderTotal').value;const subject=encodeURIComponent('小晴網站新訂單');const body=encodeURIComponent(`姓名：${name}\nEmail：${email}\n電話：${phone}\n地址：${address}\n\n商品：\n${summary}\n總計：${total}\n\n備註：${note}`);location.href=`mailto:chwang860811@gmail.com?subject=${subject}&body=${body}`}
function bind(){
 document.addEventListener('click',e=>{const v=e.target.closest('.view-product');if(v)openProduct(v.dataset.id);const a=e.target.closest('.add-product');if(a)addToCart(a.dataset.id);const r=e.target.closest('.remove-item');if(r){cart=cart.filter(x=>x.id!==r.dataset.id);saveCart();openCart()}if(e.target.closest('.open-cart'))openCart();if(e.target.closest('.checkout'))openCheckout();if(e.target.closest('.modal-close'))e.target.closest('.modal').classList.remove('show');if(e.target.classList.contains('modal'))e.target.classList.remove('show');if(e.target.closest('.menu'))$('.nav').classList.toggle('open');if(e.target.closest('.backtop'))scrollTo({top:0,behavior:'smooth'});});
 $('#productModal')?.addEventListener('click',e=>{if(e.target.closest('.qty-minus')){const n=$('.qty-num');n.textContent=Math.max(1,+n.textContent-1)}if(e.target.closest('.qty-plus'))$('.qty-num').textContent=+$('.qty-num').textContent+1;if(e.target.closest('.add-detail')){const id=$('#productModal').dataset.id;addToCart(id,+$('.qty-num').textContent);$('#productModal').classList.remove('show')}});
 $('#contactForm')?.addEventListener('submit',e=>{if(location.protocol==='file:'){e.preventDefault();const name=$('#contactName').value.trim(),email=$('#contactEmail').value.trim(),msg=$('#contactMessage').value.trim();const sub=encodeURIComponent('小晴網站聯絡訊息');const body=encodeURIComponent(`姓名：${name}\n回覆 Email：${email}\n\n訊息：\n${msg}`);location.href=`mailto:chwang860811@gmail.com?subject=${sub}&body=${body}`;toast('已開啟你的郵件程式，按「傳送」即可寄給小晴團隊。')}});
 $('#checkoutForm')?.addEventListener('submit',e=>{if(location.protocol==='file:'){e.preventDefault();toast('請先用「開始預覽.bat」或網站網址開啟，file:// 無法可靠送出表單。');return}setTimeout(()=>{cart=[];saveCart()},500)});
 updateCartCount();renderProducts();observeReveal();const pm=$('#paymentMethod');pm?.addEventListener('change',()=>$('#transferBox')?.classList.toggle('show',pm.value.includes('銀行')));
}
function observeReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('on')}),{threshold:.08});$$('.reveal:not(.on)').forEach(x=>io.observe(x))}
function gallery(){const ring=$('.ring');if(!ring)return;const imgs=['assets/avatar.jpg','assets/hero.jpg','assets/room-window.jpg','assets/room-bed.jpg','assets/character-sheet.jpg','assets/room-moodboard.png','assets/sky-dawn.svg','assets/sky-night.svg','assets/ocean-dream.svg'];const names=['小晴','夕陽房間','窗邊','晚安房間','角色設定','夢境 moodboard','晨光','星夜','海邊'];const cards=imgs.map((src,i)=>`<div class="ring-card" style="transform:rotateY(${i*40}deg) translateZ(470px)"><img src="${src}" alt="${names[i]}"><div class="ring-label"><b>${names[i]}</b></div></div>`).join('');ring.innerHTML=cards;let rot=0,drag=false,last=0;const move=d=>{if(!drag)return;rot+=(d.clientX-last)*.35;last=d.clientX;ring.style.transform=`rotateY(${rot}deg)`};ring.addEventListener('pointerdown',e=>{drag=true;last=e.clientX;ring.setPointerCapture(e.pointerId)});ring.addEventListener('pointermove',move);ring.addEventListener('pointerup',()=>drag=false);ring.addEventListener('pointercancel',()=>drag=false);$$('.rotate-left').forEach(b=>b.onclick=()=>{rot-=40;ring.style.transform=`rotateY(${rot}deg)`});$$('.rotate-right').forEach(b=>b.onclick=()=>{rot+=40;ring.style.transform=`rotateY(${rot}deg)`});}
function glow(){const g=$('.cursor-glow');if(!g)return;window.addEventListener('pointermove',e=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'})}
function scrollFx(){const b=$('.backtop');window.addEventListener('scroll',()=>b?.classList.toggle('show',scrollY>500));}
document.addEventListener('DOMContentLoaded',()=>{bind();gallery();glow();scrollFx();});
